In [ ]:
# %%
from cbspython import domain_feature_list
from IPython.display import display

import brainbodydata as bbd

In [ ]:
# %%
# Let's suppress Datalad output for this, because it generates a lot of detail.
dl_display = "disabled"

paaq = bbd.PAAQ(dl_renderer=dl_display)
vgq = bbd.VGQ(dl_renderer=dl_display)
cogs = bbd.BBCogsData(dl_renderer=dl_display)
demo = bbd.BBQuestionnaire(dl_renderer=dl_display)
ml = bbd.BBMasterList.from_frozen()

In [ ]:
# %%
# Check out the demogrpahics questionnaire data
display(demo.data.info())
demo.data.tail()

<class 'pandas.core.frame.DataFrame'>
Index: 1928 entries, a29d0b3714145d2b99fae6804dd73440 to f4eba74ad4515e209459e6f5c68ef422
Data columns (total 72 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   test_date                   1928 non-null   datetime64[ns]
 1   age                         1928 non-null   float64
 2   sex                         1926 non-null   category
 3   gender_raw                  1925 non-null   object
 4   education                   1926 non-null   category
 5   dx_diabetes                 1928 non-null   boolean
 6   dx_obesity                  1928 non-null   boolean
 7   dx_depression               1928 non-null   boolean
 8   dx_anxiety                  1928 non-null   boolean
 9   dx_hypertension             1928 non-null   boolean
 10  dx_stroke                   1928 non-null   boolean
 11  dx_hearing_loss             1928 non-null   boolean
 12  dx_heart_attack             1928 non-null   boolean
 13  dx_multiple_sclerosis       1928 non-null   boolean
 14  dx_parkinsons               1928 non-null   boolean
 15  dx_cardiac_problems         1928 non-null   boolean
 16  dx_concussion               1928 non-null   boolean
 17  dx_dementia_memory_problem  1928 non-null   boolean
 18  dx_other                    1928 non-null   boolean
 19  dx_none                     1928 non-null   boolean
 20  dx_other_str                239 non-null    object
 21  neuro_dx_adhd               1928 non-null   boolean
 22  neuro_dx_asd                1928 non-null   boolean
 23  neuro_dx_language           1928 non-null   boolean
 24  neuro_dx_cerebral_palsy     1928 non-null   boolean
 25  neuro_dx_dyslexia           1928 non-null   boolean
 26  neuro_dx_motor              1928 non-null   boolean
 27  neuro_dx_other              1928 non-null   boolean
 28  neuro_dx_none               1928 non-null   boolean
 29  neuro_dx_other_str          30 non-null     object
 30  handedness                  1885 non-null   category
 31  country                     1904 non-null   object
 32  number_languages            1879 non-null   float64
 33  household_income            1881 non-null   category
 34  economic_status             1903 non-null   category
 35  religion_buddhist           1928 non-null   boolean
 36  religion_christian          1928 non-null   boolean
 37  religion_hindu              1928 non-null   boolean
 38  religion_jewish             1928 non-null   boolean
 39  religion_muslim             1928 non-null   boolean
 40  religion_sikh               1928 non-null   boolean
 41  religion_aboriginal         1928 non-null   boolean
 42  religion_none               1928 non-null   boolean
 43  religion_other              1928 non-null   boolean
 44  religion_other_str          41 non-null     object
 45  employment                  1909 non-null   category
 46  exercise                    1900 non-null   category
 47  cigarette_vape              1888 non-null   float64
 48  caffeine                    1889 non-null   float64
 49  alcohol                     1887 non-null   float64
 50  cannabis                    1887 non-null   float64
 51  rec_drugs_none              1928 non-null   boolean
 52  rec_drugs_stimulants        1928 non-null   boolean
 53  rec_drugs_depressants       1928 non-null   boolean
 54  rec_drugs_halucinogenics    1928 non-null   boolean
 55  rec_drugs_other             1928 non-null   boolean
 56  rec_drugs_other_str         14 non-null     object
 57  phq2_1                      1882 non-null   category
 58  phq2_2                      1871 non-null   category
 59  gad2_1                      1877 non-null   category
 60  gad2_2                      1869 non-null   category
 61  num_conccussions            1878 non-null   float64
 62  hearing_aids                1899 non-null   category
 63  colourblind                 1893 non-null   object
 64  colourblind_type            52 non-null     object
 65  covid                       1897 non-null   category
 66  language                    1894 non-null   object
 67  gender_cat                  1891 non-null   category
 68  gad2                        1880 non-null   float64
 69  gad2_flag                   1928 non-null   bool
 70  phq2                        1883 non-null   float64
 71  phq2_flag                   1928 non-null   bool
dtypes: bool(2), boolean(37), category(14), datetime64[ns](1), float64(9), object(9)
memory usage: 473.4+ KB

None

,test_date,age,sex,gender_raw,education,dx_diabetes,dx_obesity,dx_depression,dx_anxiety,dx_hypertension,...,hearing_aids,colourblind,colourblind_type,covid,language,gender_cat,gad2,gad2_flag,phq2,phq2_flag
user,,,,,,,,,,,,,,,,,,,,,
a18abaecb8f65fd5ac466f6bf5242fbd,2024-06-11 13:51:56,64.0,Female,my sex is female observed not assigned no suc...,Undergraduate degree or college diploma,False,False,False,False,False,...,No,No,NaN,Yes,English,female,0.0,False,0.0,False
56fed7bb538e5692819598455cf185fa,2024-06-18 14:17:07,68.0,Male,Male,Undergraduate degree or college diploma,False,True,False,False,False,...,No,No,NaN,No,English,male,2.0,False,1.0,False
06244435e88f5e4fb0cb67553f2a6392,2024-06-18 14:58:04,43.0,Male,MALE,Graduate degree,False,False,False,False,False,...,No,No,NaN,No,English,male,2.0,False,1.0,False
9bc5dce7bce95258935e38d077b6aee2,2024-06-19 02:43:04,34.0,Male,female,High school diploma or equivalent,False,False,False,False,False,...,No,No,NaN,No,"English,African languages,Swahili",female,1.0,False,1.0,False
f4eba74ad4515e209459e6f5c68ef422,2024-06-19 05:30:54,30.0,Female,Female,Graduate degree,False,False,False,False,False,...,No,No,NaN,No,English,female,2.0,False,2.0,False

In [ ]:
# %%
# Check out the VGQ data
display(vgq.data.info())
vgq.data.tail()

<class 'pandas.core.frame.DataFrame'>
Index: 1373 entries, a29d0b3714145d2b99fae6804dd73440 to f4eba74ad4515e209459e6f5c68ef422
Data columns (total 55 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   test_date                 1373 non-null   datetime64[ns]
 1   fps_past_year             1309 non-null   category
 2   small_fps_past_year       139 non-null    category
 3   touch_fps_past_year       137 non-null    category
 4   fps_prev_year             1310 non-null   category
 5   small_fps_prev_year       232 non-null    category
 6   touch_fps_prev_year       227 non-null    category
 7   rpg_past_year             1309 non-null   category
 8   small_rpg_past_year       180 non-null    category
 9   touch_rpg_past_year       179 non-null    category
 10  rpg_prev_year             1309 non-null   category
 11  small_rpg_prev_year       253 non-null    category
 12  touch_rpg_prev_year       245 non-null    category
 13  sports_past_year          1308 non-null   category
 14  small_sports_past_year    171 non-null    category
 15  touch_sports_past_year    169 non-null    category
 16  sports_prev_year          1309 non-null   category
 17  small_sports_prev_year    264 non-null    category
 18  touch_sports_prev_year    259 non-null    category
 19  rts_past_year             1309 non-null   category
 20  small_rts_past_year       100 non-null    category
 21  touch_rts_past_year       97 non-null     category
 22  rts_prev_year             1308 non-null   category
 23  small_rts_prev_year       164 non-null    category
 24  touch_rts_prev_year       161 non-null    category
 25  roleplay_past_year        1309 non-null   category
 26  small_roleplay_past_year  107 non-null    category
 27  touch_roleplay_past_year  103 non-null    category
 28  roleplay_prev_year        1304 non-null   category
 29  small_roleplay_prev_year  146 non-null    category
 30  touch_roleplay_prev_year  142 non-null    category
 31  strategy_past_year        1309 non-null   category
 32  small_strategy_past_year  436 non-null    category
 33  touch_strategy_past_year  432 non-null    category
 34  strategy_prev_year        1306 non-null   category
 35  small_strategy_prev_year  533 non-null    category
 36  touch_strategy_prev_year  535 non-null    category
 37  music_past_year           1309 non-null   category
 38  small_music_past_year     63 non-null     category
 39  touch_music_past_year     62 non-null     category
 40  music_prev_year           1308 non-null   category
 41  small_music_prev_year     140 non-null    category
 42  touch_music_prev_year     135 non-null    category
 43  other_past_year           1307 non-null   category
 44  small_other_past_year     485 non-null    category
 45  touch_other_past_year     471 non-null    category
 46  other_prev_year           1304 non-null   category
 47  small_other_prev_year     535 non-null    category
 48  touch_other_prev_year     523 non-null    category
 49  NVGP                      1373 non-null   bool
 50  AVGP_1                    1373 non-null   bool
 51  AVGP_2                    1373 non-null   bool
 52  AVGP_3                    1373 non-null   bool
 53  AVGP_4                    1373 non-null   bool
 54  Low_Tweener               1373 non-null   bool
dtypes: bool(6), category(48), datetime64[ns](1)
memory usage: 101.2+ KB

None

,test_date,fps_past_year,small_fps_past_year,touch_fps_past_year,fps_prev_year,small_fps_prev_year,touch_fps_prev_year,rpg_past_year,small_rpg_past_year,touch_rpg_past_year,...,touch_other_past_year,other_prev_year,small_other_prev_year,touch_other_prev_year,NVGP,AVGP_1,AVGP_2,AVGP_3,AVGP_4,Low_Tweener
user,,,,,,,,,,,,,,,,,,,,,
b1daed7f17525116815e2a8913aa1b88,2024-06-18 07:06:54,Never,NaN,NaN,Never,NaN,NaN,Never,NaN,NaN,...,NaN,Never,NaN,NaN,True,False,False,False,False,False
362f0720ae185cdc844390a408b582c9,2024-06-18 08:46:27,Never,NaN,NaN,Never,NaN,NaN,Never,NaN,NaN,...,NaN,Never,NaN,NaN,True,False,False,False,False,False
b4055c6b4d565522a549542037acf75b,2024-06-18 09:40:24,Never,NaN,NaN,Never,NaN,NaN,Never,NaN,NaN,...,NaN,Never,NaN,NaN,True,False,False,False,False,False
06244435e88f5e4fb0cb67553f2a6392,2024-06-18 16:05:52,Never,NaN,NaN,Never,NaN,NaN,Never,NaN,NaN,...,NaN,Never,NaN,NaN,True,False,False,False,False,False
f4eba74ad4515e209459e6f5c68ef422,2024-06-19 06:27:45,Never,NaN,NaN,Never,NaN,NaN,Never,NaN,NaN,...,Yes,Between 1 - 3 hours,Yes,Yes,True,False,False,False,False,False

In [ ]:
# %%
# Check out the PAAQ data
display(paaq.data.info())
paaq.data.tail()

<class 'pandas.core.frame.DataFrame'>
Index: 1312 entries, a29d0b3714145d2b99fae6804dd73440 to f4eba74ad4515e209459e6f5c68ef422
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   test_date               1312 non-null   datetime64[ns]
 1   transportation          1310 non-null   category
 2   transportation_hours    942 non-null    float64
 3   transportation_minutes  942 non-null    float64
 4   recreation              1312 non-null   object
 5   recreation_sweat        955 non-null    category
 6   recreation_hours        878 non-null    float64
 7   recreation_minutes      878 non-null    float64
 8   other                   1306 non-null   category
 9   other_sweat             855 non-null    category
 10  other_hours             494 non-null    float64
 11  other_minutes           494 non-null    float64
 12  vigorous                1305 non-null   category
 13  vigorous_hours          771 non-null    float64
 14  vigorous_minutes        771 non-null    float64
 15  similar_to_last_month   1303 non-null   category
 16  fitness_tracker         1300 non-null   category
 17  fitness_tracker_months  386 non-null    float64
 18  total_pa_minutes        1311 non-null   float64
 19  transportation_total    942 non-null    float64
 20  recreation_total        878 non-null    float64
 21  other_total             494 non-null    float64
 22  vigorous_total          771 non-null    float64
dtypes: category(7), datetime64[ns](1), float64(14), object(1)
memory usage: 184.2+ KB

None

,test_date,transportation,transportation_hours,transportation_minutes,recreation,recreation_sweat,recreation_hours,recreation_minutes,other,other_sweat,...,vigorous_hours,vigorous_minutes,similar_to_last_month,fitness_tracker,fitness_tracker_months,total_pa_minutes,transportation_total,recreation_total,other_total,vigorous_total
user,,,,,,,,,,,,,,,,,,,,,
b1daed7f17525116815e2a8913aa1b88,2024-06-18 06:53:50,No,NaN,NaN,Yes,Yes,0.0,30.0,Yes,Yes,...,0.0,30.0,No,Apple Watch,22.0,270.0,NaN,30.0,240.0,30.0
362f0720ae185cdc844390a408b582c9,2024-06-18 08:41:37,Yes,4.0,0.0,No,NaN,NaN,NaN,Yes,Yes,...,NaN,NaN,No,None,NaN,420.0,240.0,NaN,180.0,NaN
b4055c6b4d565522a549542037acf75b,2024-06-18 09:38:49,No,NaN,NaN,Yes,No,NaN,NaN,Yes,No,...,NaN,NaN,Yes,None,NaN,0.0,NaN,NaN,NaN,NaN
06244435e88f5e4fb0cb67553f2a6392,2024-06-18 16:03:08,No,NaN,NaN,No,NaN,NaN,NaN,Yes,Yes,...,NaN,NaN,No,None,NaN,60.0,NaN,NaN,60.0,NaN
f4eba74ad4515e209459e6f5c68ef422,2024-06-19 06:21:34,No,NaN,NaN,Yes,Yes,4.0,0.0,Yes,Yes,...,1.0,30.0,Yes,Apple Watch,18.0,300.0,NaN,240.0,60.0,90.0

In [ ]:
# %%
# And finally the cog scores
display(cogs.scores.info(max_cols=1000))
cogs.scores.tail()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1456 entries, ('00381505392853ebae5e245f3a33ccb2', np.int64(202997113), Timestamp('2024-01-19 00:00:00'), 'randomization3') to ('fff36120f04f5423a3fa5964e51b78ce', np.int64(202111988), Timestamp('2024-01-14 00:00:00'), 'randomization3')
Data columns (total 129 columns):
 #    Column                      Non-Null Count  Dtype
---   ------                      --------------  -----
 0    SS_max_score                1369 non-null   float64
 1    SS_avg_score                1365 non-null   float64
 2    SS_avg_ms_per_item          1365 non-null   float64
 3    SS_num_errors               1369 non-null   float64
 4    SS_num_correct              1369 non-null   float64
 5    SS_num_attempts             1369 non-null   float64
 6    SS_accuracy                 1369 non-null   float64
 7    SS_avg_ms_correct           1365 non-null   float64
 8    SS_std_ms_correct           1365 non-null   float64
 9    GR_final_score              1383 non-null   float64
 10   GR_num_errors               1383 non-null   float64
 11   GR_num_correct              1383 non-null   float64
 12   GR_num_attempts             1383 non-null   float64
 13   GR_accuracy                 1382 non-null   float64
 14   GR_avg_ms_correct           1382 non-null   float64
 15   GR_std_ms_correct           1382 non-null   float64
 16   DT_final_score              1421 non-null   float64
 17   DT_pct_CC                   1421 non-null   float64
 18   DT_pct_CI                   1421 non-null   float64
 19   DT_pct_IC                   1421 non-null   float64
 20   DT_pct_II                   1421 non-null   float64
 21   DT_RT_CC                    1421 non-null   float64
 22   DT_RT_CI                    1421 non-null   float64
 23   DT_RT_IC                    1421 non-null   float64
 24   DT_RT_II                    1421 non-null   float64
 25   DT_IR_RT                    1421 non-null   float64
 26   DT_IR_errors                1421 non-null   float64
 27   DT_ncorrect_CC              1421 non-null   float64
 28   DT_ncorrect_II              1421 non-null   float64
 29   DT_num_errors               1421 non-null   float64
 30   DT_num_correct              1421 non-null   float64
 31   DT_num_attempts             1421 non-null   float64
 32   DT_accuracy                 1418 non-null   float64
 33   DT_avg_ms_correct           1417 non-null   float64
 34   DT_std_ms_correct           1417 non-null   float64
 35   OOO_final_score             1408 non-null   float64
 36   OOO_max                     1408 non-null   float64
 37   OOO_num_errors              1408 non-null   float64
 38   OOO_num_correct             1408 non-null   float64
 39   OOO_num_attempts            1408 non-null   float64
 40   OOO_accuracy                1407 non-null   float64
 41   OOO_avg_ms_correct          1407 non-null   float64
 42   OOO_std_ms_correct          1407 non-null   float64
 43   ML_max_score                1405 non-null   float64
 44   ML_avg_score                1405 non-null   float64
 45   ML_avg_ms_per_item          1405 non-null   float64
 46   ML_num_errors               1405 non-null   float64
 47   ML_num_correct              1405 non-null   float64
 48   ML_num_attempts             1405 non-null   float64
 49   ML_accuracy                 1405 non-null   float64
 50   ML_avg_ms_correct           1405 non-null   float64
 51   ML_std_ms_correct           1405 non-null   float64
 52   RT_final_score              1392 non-null   float64
 53   RT_max                      1392 non-null   float64
 54   RT_correct_score            1392 non-null   float64
 55   RT_num_errors               1392 non-null   float64
 56   RT_num_correct              1392 non-null   float64
 57   RT_num_attempts             1392 non-null   float64
 58   RT_accuracy                 1391 non-null   float64
 59   RT_avg_ms_correct           1391 non-null   float64
 60   RT_std_ms_correct           1391 non-null   float64
 61   FM_final_score              1404 non-null   float64
 62   FM_max                      1404 non-null   float64
 63   FM_correct_score            1404 non-null   float64
 64   FM_num_errors               1404 non-null   float64
 65   FM_num_correct              1404 non-null   float64
 66   FM_num_attempts             1404 non-null   float64
 67   FM_accuracy                 1402 non-null   float64
 68   FM_avg_ms_correct           1402 non-null   float64
 69   FM_std_ms_correct           1402 non-null   float64
 70   DS_max_score                1378 non-null   float64
 71   DS_avg_score                1371 non-null   float64
 72   DS_avg_ms_per_item          1371 non-null   float64
 73   DS_num_errors               1378 non-null   float64
 74   DS_num_correct              1378 non-null   float64
 75   DS_num_attempts             1378 non-null   float64
 76   DS_accuracy                 1378 non-null   float64
 77   DS_avg_ms_correct           1371 non-null   float64
 78   DS_std_ms_correct           1371 non-null   float64
 79   SP_final_score              1376 non-null   float64
 80   SP_num_errors               1376 non-null   float64
 81   SP_num_correct              1376 non-null   float64
 82   SP_num_attempts             1376 non-null   float64
 83   SP_accuracy                 1362 non-null   float64
 84   SP_avg_ms_correct           1355 non-null   float64
 85   SP_std_ms_correct           1355 non-null   float64
 86   PA_max_score                1402 non-null   float64
 87   PA_avg_score                1398 non-null   float64
 88   PA_avg_ms_per_item          1398 non-null   float64
 89   PA_num_errors               1402 non-null   float64
 90   PA_num_correct              1402 non-null   float64
 91   PA_num_attempts             1402 non-null   float64
 92   PA_accuracy                 1402 non-null   float64
 93   PA_avg_ms_correct           1398 non-null   float64
 94   PA_std_ms_correct           1398 non-null   float64
 95   PO_final_score              1392 non-null   float64
 96   PO_num_errors               1392 non-null   float64
 97   PO_num_correct              1392 non-null   float64
 98   PO_num_attempts             1392 non-null   float64
 99   PO_accuracy                 1391 non-null   float64
 100  PO_avg_ms_correct           1391 non-null   float64
 101  PO_std_ms_correct           1391 non-null   float64
 102  TS_max_score                1375 non-null   float64
 103  TS_avg_score                1373 non-null   float64
 104  TS_avg_ms_per_item          1373 non-null   float64
 105  TS_num_errors               1375 non-null   float64
 106  TS_num_correct              1375 non-null   float64
 107  TS_num_attempts             1375 non-null   float64
 108  TS_accuracy                 1375 non-null   float64
 109  TS_avg_ms_correct           1373 non-null   float64
 110  TS_std_ms_correct           1373 non-null   float64
 111  SAR_final_score             1357 non-null   float64
 112  SAR_nogo_success            1357 non-null   float64
 113  SAR_go_success              1357 non-null   float64
 114  SAR_num_commissions         1357 non-null   float64
 115  SAR_pct_commissions         1357 non-null   float64
 116  SAR_num_omissions           1357 non-null   float64
 117  SAR_pct_omissions           1357 non-null   float64
 118  SAR_num_anticipatory        1357 non-null   float64
 119  SAR_num_ambiguous           1357 non-null   float64
 120  SAR_avg_RT_go               1357 non-null   float64
 121  SAR_std_RT_go               1357 non-null   float64
 122  SAR_RT_cv                   1357 non-null   float64
 123  SAR_avg_RT_b4_nogo_success  1357 non-null   float64
 124  SAR_avg_RT_b4_nogo_fail     1357 non-null   float64
 125  SAR_post_CE_slowing         861 non-null    float64
 126  SAR_num_errors              1357 non-null   float64
 127  SAR_num_correct             1357 non-null   float64
 128  SAR_num_attempts            1357 non-null   float64
dtypes: float64(129)
memory usage: 1.5+ MB

None

,,,,SS_max_score,SS_avg_score,SS_avg_ms_per_item,SS_num_errors,SS_num_correct,SS_num_attempts,SS_accuracy,SS_avg_ms_correct,SS_std_ms_correct,GR_final_score,...,SAR_num_ambiguous,SAR_avg_RT_go,SAR_std_RT_go,SAR_RT_cv,SAR_avg_RT_b4_nogo_success,SAR_avg_RT_b4_nogo_fail,SAR_post_CE_slowing,SAR_num_errors,SAR_num_correct,SAR_num_attempts
user,report,test_date,batch_name,,,,,,,,,,,,,,,,,,,,,
ff1709fec6275fd5b85f8144bb8a4a66,206425862,2024-02-09,randomization5,4.0,3.666667,2543.944444,3.0,3.0,6.0,0.500,9277.666667,844.756901,19.0,...,0.0,888.280,81.413,10.911,911.125,0.000,NaN,0.0,225.0,225.0
ff3840244d76543d943a1a596e470411,202132888,2024-01-14,randomization3,6.0,4.800000,1868.506667,3.0,5.0,8.0,0.625,8990.200000,1579.555305,23.0,...,1.0,682.775,81.508,8.377,678.472,647.833,-7.0,5.0,220.0,225.0
ff42e193c2a758da9169e614970b0992,201819924,2024-01-12,randomization4,5.0,4.333333,2097.416667,3.0,3.0,6.0,0.500,9058.000000,701.604352,22.0,...,2.0,894.101,138.224,6.468,960.550,876.750,65.5,5.0,220.0,225.0
ffba85f32aea5f76ae26209d37c0e6cb,201722735,2024-01-11,randomization5,5.0,4.500000,2538.525000,3.0,2.0,5.0,0.400,11383.000000,906.000000,16.0,...,17.0,871.403,354.649,2.457,977.545,0.000,276.0,25.0,200.0,225.0
fff36120f04f5423a3fa5964e51b78ce,202111988,2024-01-14,randomization3,6.0,5.000000,1969.172222,3.0,3.0,6.0,0.500,9809.333333,1398.426815,20.0,...,1.0,783.670,114.921,6.819,786.962,0.000,NaN,0.0,225.0,225.0

In [ ]:
# %%
# Might as well take a look at the primary test scores, too.
cogs.scores[domain_feature_list(abbreviated=True)].describe().T

                 count        mean        std   min   25%    50%    75%    max
SS_max_score    1369.0    5.474069   1.105981   0.0   5.0    5.0    6.0    9.0
GR_final_score  1383.0   17.524223   5.320885  -8.0  14.0   18.0   21.0   34.0
DT_final_score  1421.0   20.778325  15.897585 -19.0   6.0   22.0   34.0   80.0
OOO_max         1408.0   15.464489   2.261231   0.0  14.0   16.0   17.0   20.0
ML_max_score    1405.0    7.333808   1.288356   2.0   7.0    7.0    8.0   16.0
RT_final_score  1392.0   75.121408  35.720040 -23.0  51.0   74.0   98.0  244.0
FM_final_score  1404.0  108.897436  33.029364   0.0  88.0  110.0  132.0  400.0
DS_max_score    1378.0    6.774311   1.581669   0.0   6.0    7.0    8.0   19.0
SP_final_score  1376.0   19.082849   9.050186   0.0  14.0   18.0   24.0   60.0
PA_max_score    1402.0    4.483595   1.037527   0.0   4.0    4.0    5.0   10.0
PO_final_score  1392.0   38.288793  20.789588 -11.0  23.0   37.0   52.0  152.0
TS_max_score    1375.0    7.802182   1.786288   0.0   7.0    8.0    9.0   17.0

In [ ]:
# %%
users = bbd.BBMasterList.from_frozen()
display(users.data)

,stage,user,creation_date,giftcard_entry
0,debriefing_complete,ba40524a9f25561181ec6030662fc2fe,2024-01-15,Yes
1,consented,0125dff1303d5a0884a259fbc1a48e0a,2024-01-13,NaN
2,debriefing_complete,878e646225225fa696242c7e86eb0b43,2024-02-22,Yes
3,debriefing_complete,c228eafe91df5c578ddff277579f932e,2024-02-22,Yes
4,demographics_complete,1f92cdc518955890a08178a178b24efb,2024-05-22,Yes
...,...,...,...,...
2580,consented,66d32906b28a567298e11f353e884811,2024-06-18,NaN
2581,debriefing_complete,8b371223051553e7975775f2fa02ef98,2024-01-16,Yes
2582,debriefing_complete,203f78f8abb759969b6b36442f33c77c,2024-01-12,Yes
2583,debriefing_complete,73f4a78b9b6956ada02880e63cf82105,2024-01-12,Yes
2584,demographics_complete,47ae8ba9128653de8bde10814e6de99f,2024-05-18,No